# .rubocop.yml

AllCops:
  NewCops: enable

Naming/MethodParameterName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
